Repository berachain/polaris, pull requests merged in 2023-11, with the labels that each got.

#1296 chore(deps): Move to cosmos-sdk `v0.50` official release
  README.md
  build/tools/go.mod
  build/tools/go.sum
  cosmos/go.mod
  cosmos/go.sum
  e2e/precompile/go.mod
  e2e/precompile/go.sum
  e2e/testapp/go.mod
  e2e/testapp/go.sum
  e2e/testapp/polard/cmd/commands.go
  e2e/testapp/polard/cmd/root.go
  eth/go.mod
  eth/go.sum
  go.work.sum
Labels: merge me daddy, backport/v0.0.1-alpha

#1298 fix(readme): fix folder structure
  README.md
Labels: merge me daddy, backport/v0.0.1-alpha

#1300 fix(cosmos): Avoid usage of sdk.NewCoin to prevent unnecessary panics
  cosmos/lib/conversions.go
Labels: merge me daddy, backport/v0.0.1-alpha

#1303 chore(precompile): Protect precompile panics from halting chain
  cosmos/x/evm/plugins/precompile/plugin.go
  cosmos/x/evm/plugins/precompile/plugin_test.go
  cosmos/x/evm/plugins/precompile/recovery.go
Labels: merge me daddy, backport/v0.0.1-alpha

#1307 fix(eth/polar): fix typos
  eth/core/precompile/method.go
  eth/eth.go
  eth/node/node.go
  eth/polar/api/web3.go
  eth/polar/api_backend.go
  eth/polar/backend.go
  eth/version/version.go
Labels: merge me daddy, backport/v0.0.1-alpha

#1316 chore(license): add `rollkit` license.
  license/rollkit.md
Labels: merge me daddy

#1318 fix(mempool): allow sdk.Tx's to not fail `checkTx`
  cosmos/runtime/txpool/mempool.go
  cosmos/runtime/txpool/mempool_test.go
Labels: merge me daddy, backport/v0.0.1-alpha

#1324 feat(test): Added test to call contract's read method
  e2e/hive/simulators/rpc/ethclient.hive
Labels: merge me daddy, testing, backport/v0.0.2-alpha

#1325 chore: fix typos in comment
  cosmos/runtime/chain/chain.go
  cosmos/runtime/runtime.go
  cosmos/runtime/txpool/mempool.go
Labels: merge me daddy, backport/v0.0.2-alpha

#1328 chore(txpool): fix typo
  cosmos/runtime/txpool/handler.go
Labels: merge me daddy, backport/v0.0.2-alpha

#1338 fix: fix the wrong description about `polard` binary
  e2e/testapp/polard/cmd/root.go
Labels: merge me daddy, backport/v0.0.2-alpha
